SELECT UPPER(OGRAD) AS 'ÖÐRENCÝ AD', UPPER(OGRSOYAD) AS 'SOYAD', LOWER(OGRSEHIR) AS 'ÞEHÝR'
FROM TBLOGRENCILER

SELECT LOWER(OGRAD) AS 'AD',LOWER(OGRSOYAD) AS 'SOYAD', LOWER(KULUPAD) AS 'KULÜP' FROM TBLOGRENCILER
INNER JOIN TBLKULUPLER ON TBLKULUPLER.KULUPID=TBLOGRENCILER.OGRKULUP
WHERE OGRSEHIR='ADANA' AND OGRKULUP=1

SELECT SUBSTRING(OGRAD,1,1) + '. ' + OGRSOYAD AS 'AD SOYAD', SUBSTRING(KULUPAD,1,3) AS 'KULÜP ADI' FROM TBLOGRENCILER
INNER JOIN TBLKULUPLER ON TBLKULUPLER.KULUPID=TBLOGRENCILER.OGRKULUP

SELECT LEFT('MERHABA DÜNYA', 9) AS 'SOL', RIGHT('MERHABA  ÝSTANBUL', 2)

SELECT LEFT(OGRAD,1) + '. ' + OGRSOYAD AS 'AD SOYAD' FROM TBLOGRENCILER

SELECT DERSAD,LEFT(AVG(ORTALAMA),5) FROM TBLNOTLAR
INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID=TBLNOTLAR.DERS
GROUP BY DERSAD

SELECT LEN('MERHABA')

SELECT OGRAD,LEN(OGRAD) FROM TBLOGRENCILER WHERE OGRSEHIR='ADANA' AND
OGRKULUP=(SELECT KULUPID FROM TBLKULUPLER WHERE KULUPAD='Biliþim')

SELECT * FROM TBLOGRENCILER WHERE LEN(OGRAD+OGRSOYAD)=3 OR LEN(OGRAD+OGRSOYAD)=7

SELECT LTRIM('		Korkma Sönmez Bu Þafaklardan Al Sancak')
SELECT RTRIM('Korkma Sönmez Bu Þafaklardan Al Sancak		')

SELECT REPLACE('Nurgül Fýrat','Fýrat','Kakýz')

--1.Parametre Ana Kelime Cümle
--2.Parametre Bulunacak Deðer
--3.Parametre Yeni Deðer
SELECT REPLACE('Merhaba bugün hava soðuk','ð','g')

SELECT CHARINDEX('e','SQL Derslerine Devam Ediyoruz', 15)

SELECT CHARINDEX('a',OGRAD) FROM TBLOGRENCILER

SELECT REVERSE('NURGÜL')
SELECT REVERSE(DERSAD) FROM TBLDERSLER