
SELECT * FROM  TBLHAREKET

SELECT URUNAD,COUNT(*) AS 'ÜRÜN AD' FROM TBLHAREKET 
INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID
GROUP BY URUNAD ORDER BY COUNT(*)

SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE
KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BiLGiSAYAR'))

SELECT * FROM TBLHAREKET WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ADANA')

SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE
KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))

SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN (SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR IN ('ADANA','ANKARA'))
 
 SELECT * FROM TBLHAREKET WHERE URUN=1

 UPDATE TBLURUNLER SET URUNSTOK=URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE URUN=10) WHERE URUNID=10

 CREATE TABLE KASA 
 (
 TOPLAM decimal(18,2)
 )

 INSERT INTO TBLKASA VALUES(0)
 SELECT * FROM TBLKASA
 UPDATE TBLKASA SET TOPLAM=(SELECT SUM(TUTAR) FROM TBLHAREKET)