SELECT AVG(ORTALAMA) FROM TBLNOTLAR WHERE DERS=1

--Sýnýf ortalamasýnýn altýnda olan öðrencilerin "Durum2" sütunlarýnýn yanýna "Altýnda"
--aksi durumda "Üstünde" yazdýran sorgu

SELECT *, 'Üstünde' as 'DURUM2' FROM TBLNOTLAR
WHERE ORTALAMA>(SELECT AVG(ORTALAMA) FROM TBLNOTLAR)
UNION
SELECT *,'Altýnda' as 'DURUM2' FROM TBLNOTLAR
WHERE ORTALAMA<(SELECT AVG(ORTALAMA) FROM TBLNOTLAR)


--ABS (MUTLAK DEÐER), POWER(ÜS ALMA), SQRT(KAREKÖK)
--FLOOR(TABAN), CEILING(TAVAN)
SELECT ABS(-85) AS 'MUTLAK'
SELECT POWER(2,4) AS 'ÜS ALMA'
SELECT SQRT(625) AS 'KAREKÖK'
SELECT FLOOR(4.86) AS 'TABAN', CEILING(4.86) AS 'TAVAN'

SELECT POWER(SINAV1,2) FROM TBLNOTLAR

SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1
SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM TBLNOTLAR
INNER JOIN TBLDERSLER ON TBLNOTLAR.DERS=TBLDERSLER.DERSID
WHERE OGRENCI=(SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='ALÝ' AND OGRSOYAD='YILDIRIM')