SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3

SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND
MUSTERI=(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ANKARA')

SELECT DATENAME(MONTH,GETDATE()), DATENAME(WEEKDAY,'1991.02.03')

SELECT DATEDIFF(YEAR,'2010.03.02',GETDATE())
SELECT DATEDIFF(MONTH,'2010.10.14','2015.08.06')
SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBLHAREKET WHERE HAREKETID=1

SELECT DATEADD(YEAR,3,'2021.03.02')
SELECT DATEADD(DAY,45,GETDATE())
SELECT DATEADD(MONTH,350,GETDATE())