
--create database SatisVT

use SatisVT
Create Table TBLKATEGORI
(
KATEGORIID tinyint identity(1,1) primary key,
KATEGORIAD varchar(50)
)

Create Table TBLURUNLER
(
URUNID int identity(1,1) primary key,
URUNAD varchar(50),
URUNMARKA varchar(50),
KATEGORI tinyint,
URUNALISFIYAT decimal(18,2),
URUNSATISFIYAT decimal(18,2),
URUNSTOK smallint check(URUNSTOK>0),
URUNDURUM bit default '1'
)

Create Table TBLPERSONEL
(
PERSONELID smallint identity(1,1) primary key,
PERSONELADSOYAD varchar(50)
)

Create Table TBLMUSTERI
(
MUSTERIID int identity(1,1) primary key,
MUSTERIAD varchar(50),
MUSTERISOYAD varchar(50),
MUSTERISEHIR varchar(13),
MUSTERIBAKIYE decimal(18,2)
)

Create Table TBLHAREKET
(
HAREKETID int identity(1,1) primary key,
URUN int,
MUSTERI int,
PERSONEL smallint,
ADET int,
TUTAR decimal(18,2),
TARIH smalldatetime
)

--TRUNCATE TABLE TBLURUNLER

INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES('BÝLGÝSAYAR')
INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES('BEYAZ EÞYA')
INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES('KÜÇÜK EV ALETÝ')
INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES('TV')

INSERT INTO TBLURUNLER(URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK)
VALUES('BUZDOLABI','SIEMENS',2,4356,4588,10)

SELECT * FROM TBLURUNLER
UPDATE TBLURUNLER SET URUNAD='SU ISITICI' WHERE URUNAD='KETTLE' 

SELECT KATEGORIAD,COUNT(*) FROM TBLURUNLER
INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID GROUP BY KATEGORIAD ORDER BY COUNT(*)

UPDATE TBLURUNLER SET URUNSATISFIYAT+=500
WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR')

UPDATE TBLURUNLER SET URUNSATISFIYAT -= (URUNSATISFIYAT*10/100)
WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='TV')

SELECT COUNT(*) AS 'KAÇ FARKLI ÜRÜN', SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER
SELECT * FROM TBLURUNLER

SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK,
(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR',
(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR'
FROM TBLURUNLER
INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID

UPDATE TBLURUNLER SET URUNSATISFIYAT += (URUNSATISFIYAT*20/100)
WHERE ((URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK)<1000
