SELECT COUNT(*) AS 'TOPLAM KAYIT' FROM TBLOGRENCILER

SELECT SUM(SINAV1) AS 'TOPLAM',SUM(SINAV2),SUM(SINAV3) FROM TBLNOTLAR
SELECT AVG(SINAV1) AS 'ORTALAMA',AVG(SINAV2),AVG(SINAV3) FROM TBLNOTLAR
SELECT MAX(SINAV1) AS 'MAXIMUM', MAX(SINAV2),MAX(SINAV3) FROM TBLNOTLAR
SELECT MIN(SINAV1) AS 'MINIMUM', MIN(SINAV2),MIN(SINAV3) FROM TBLNOTLAR

SELECT OGRSEHIR,COUNT(*) AS 'TOPLAM' FROM TBLOGRENCILER GROUP BY OGRSEHIR

SELECT DURUM,COUNT(*) AS 'GEÇEN-KALAN' FROM TBLNOTLAR GROUP BY DURUM

UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3

UPDATE TBLNOTLAR SET DURUM='False' where ORTALAMA<50

SELECT OGRKULUP,COUNT(*) FROM TBLOGRENCILER GROUP BY OGRKULUP

SELECT OGRSEHIR,COUNT(*) AS 'SAYI'
FROM TBLOGRENCILER
GROUP BY OGRSEHIR HAVING COUNT(*)=2



SELECT DURUM,COUNT(*) AS 'GEÇENLER' 
FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM='True'

SELECT DURUM,COUNT(*) AS 'KALANLAR' 
FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM='False'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%A%' OR OGRSOYAD LIKE '%A%'

SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE 'A%' and OGRCINSIYET='Erkek'
SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE 'A%' and OGRCINSIYET='Kýz'

SELECT DISTINCT OGRSEHIR FROM TBLOGRENCILER
SELECT COUNT(DISTINCT(OGRSEHIR)) AS 'ÞEHÝR SAYISI' FROM TBLOGRENCILER

SELECT DISTINCT OGRKULUP FROM TBLOGRENCILER
SELECT COUNT(DISTINCT(OGRKULUP)) AS 'KULÜP SAYISI' FROM TBLOGRENCILER

SELECT * FROM TBLOGRENCILER ORDER BY OGRAD

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR LIKE '%AN%'
SELECT * FROM TBLOGRENCILER WHERE OGRAD LIKE '%[N,I]%'
SELECT * FROM TBLOGRENCILER WHERE OGRKULUP LIKE '[A-H]%'
SELECT * FROM TBLOGRENCILER WHERE OGRKULUP LIKE '%[K-M]'

SELECT TOP 4 * FROM TBLOGRENCILER  ORDER BY OGRID DESC
SELECT TOP 60 PERCENT * FROM TBLOGRENCILER

SELECT * FROM TBLOGRENCILER WHERE OGRSEHIR IN('ÝZMÝR','ANKARA','ADANA')
SELECT * FROM TBLNOTLAR WHERE SINAV1 NOT IN(75,80,85,90)

SELECT * FROM TBLNOTLAR WHERE ORTALAMA BETWEEN 74 AND 100
SELECT * FROM TBLOGRENCILER WHERE OGRAD BETWEEN 'A' AND 'O'
SELECT * FROM TBLOGRENCILER WHERE OGRAD NOT BETWEEN 'A' AND 'O'

UPDATE TBLOGRENCILER SET OGRKULUP=4 WHERE OGRKULUP='Gezi'