
CREATE PROCEDURE HAREKETLER
AS
SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'MÜÞTERÝ AD SOYAD', 
PERSONELADSOYAD AS 'PERSONEL AD SOYAD',ADET,TUTAR,TARIH
FROM TBLHAREKET
INNER JOIN TBLURUNLER ON TBLHAREKET.URUN=TBLURUNLER.URUNID
INNER JOIN TBLMUSTERI ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
INNER JOIN TBLPERSONEL ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

EXECUTE HAREKETLER

--CREATE PROCEDURE DENEME
--AS
--SELECT * FROM TBLURUNLER WHERE URUNSTOK>10

--EXEC DENEME

--DROP PROCEDURE DENEME

ALTER PROCEDURE URUNGETIR
@Deger varchar(50)='BUZDOLABI'
AS
SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
WHERE URUNAD=@Deger

EXEC URUNGETIR @Deger='LAPTOP'